function [fitresult, gof] = createSeasonalFit(ST)
%CREATEFIT(ST)
%  Create a fit.
%
%  Data for 'seasonalFit' fit:
%      Y Output: ST
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jan-2025 21:58:57


%% Fit: 'seasonalFit'.
[xData, yData] = prepareCurveData( [], ST );

% Set up fittype and options.
ft = fittype( 'sin2' );
opts = fitoptions( 'Method', 'NonlinearLeastSquares' );
opts.Display = 'Off';
opts.Lower = [-Inf 0 -Inf -Inf 0 -Inf];
opts.Robust = 'Bisquare';
opts.StartPoint = [0.0834904408958904 0.525905378133974 -3.07182815646997 0.0146685024134236 0.553584608562078 1.86521488636361];

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts );

% Plot fit with data.
figure( 'Name', 'seasonalFit' );
h = plot( fitresult, xData, yData );
legend( h, 'seasonal', 'seasonalFit', 'Location', 'Best', 'Interpreter', 'none' );
% Label axes
ylabel( 'seasonal', 'Interpreter', 'none' );
title("Seasonal Component Fit")
grid on


