function [fitresult, gof] = createLongTermFit(LT)
%CREATEFIT(LT)
%  Create a fit.
%
%  Data for 'longTermFit' fit:
%      Y Output: LT
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 18-Jan-2025 22:00:06


%% Fit: 'longTermFit'.
[xData, yData] = prepareCurveData( [], LT );

% Set up fittype and options.
ft = fittype( 'poly1' );

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft );

% Plot fit with data.
figure( 'Name', 'longTermFit' );
h = plot( fitresult, xData, yData );
legend( h, 'longTerm', 'longTermFit', 'Location', 'Best', 'Interpreter', 'none' );
% Label axes
ylabel( 'longTerm', 'Interpreter', 'none' );
grid on
title("Long Term Component Fit")


